plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.0.1-rc.2.cjs

packageExtensions:
  "@linaria/webpack-loader@*":
    peerDependencies:
      "@babel/core": "*"
      "@linaria/shaker": "*"
  "@linaria/babel-preset@*":
    dependencies:
      "@babel/plugin-transform-modules-commonjs": "*"
      "@babel/plugin-proposal-export-namespace-from": "*"
    peerDependencies:
      "@linaria/shaker": "*"
  "@linaria/preeval@*":
    peerDependencies:
      "@linaria/shaker": "*"
  "@linaria/webpack4-loader@*":
    peerDependencies:
      "@linaria/shaker": "*"
  "@linaria/webpack5-loader@*":
    peerDependencies:
      "@linaria/shaker": "*"
  "@stylelint/postcss-markdown@*":
    peerDependencies:
      "postcss-html": "*"